#+startup: indent show2levels
#+title:
#+author masayuki
* 数理のひろがりシラバス

** 関連ページ
*** 他のシラバス
reference/

*** ICU 文系用
数学の方法
[[https://ocw.info.icu.ac.jp/_/search?query=Instructor%3A%20SUZUKI%E2%80%9A%20Hiroshi%20%E9%88%B4%E6%9C%A8%E5%AF%9B&scope=site&showTabs=false&page_token=CJfazZrvLxAA][Home]]

*** 数理科学基礎 東京大学
** 質問・相談方法
面談は，図書館2階の学修支援コーナーに来てください。
学期中の木曜日と金曜日 14時から17時に在席しています。

Webclass のメッセージでも受付けます。

メールでの質問・相談にもできるかぎり応じます。
suzuki@iwate-u.ac.jp 宛にメールしてください

** キーワード

集合，論理，関数，関係，
グラフと思考と理解，論理的思考法・発想法・GTD
微分，積分，微分方程式
ベクトルと行列

** 授業の目的
大学で学ぶ数学分野で用いられる基礎的な概念と言葉を知ること。
数学の言葉として，集合，論理，関係，関数，グラフを知ること。
論理的思考法について，関係とグラフを用いて，捉えること。
関数とその変化を表す微積分の考え方を知ること。
多変数その変化を表す微積分の考え方を知ること。
多変数の方程式の解法について，行列とベクトルで考えること。

あわせて，数学的ICT (情報処理技術) の考え方と技術を学ぶこと。

** 到達目標

自然科学を記述するための数理論理学の表現方法とその意味について理解する
こと。それらは，論理，集合，関数，関係，グラフなど。

論理的思考技術について，論理，集合，関数，関係，グラフを用いて，考えら
れるようになること。

状態や関係およびその変化を，微分や積分を用いて，理解できるようになるこ
と。

多変数の場合についても同様に，行列とベクトルを用いた表現を，理解できる
ようになること。

** 授業の概要

まず，集合，関数，関係，グラフについて学びます。
これらに関しては，オンラインコンテンツを提示しますの
で，それを手元のノートパソコンで閲覧してください。

次に，論理的思考とグラフについて考えます。これには，講師による過去の放
送大学での講義コンテンツを用います。

微積分，微分方程式，線形代数については，それぞれの科目の教科書を参考に
してください。講師による図的な説明も行います。


受講に必要と思われる情報処理技術 (ICT) は，情報基礎の進行を考慮して，
毎回，序々に進めていくつもりです。
具体的な内容は，皆さんの様子に合せて，決めていきたいと思います。
大切なことは，ウェブの閲覧技術，作業記録を残す技術，数理情報文書作成技
術，だと思います。

** 授業形式

下記のことを毎回行なう予定です：

- 教材 (オンラインコンテンツ) の講師による講義形式の説明，
- 教材の学生自身での学び，
- Web検索等による確かめ，
- 講師と学生自身でのまとめの作成，
- 毎回少しの時間を取り，持ち込みパソコンを使って，数理ICT入門を行なう
  予定 (講義室のネットワーク環境に依存しますが)

  
** 授業外学修
毎回の受講して得た知識を復習し，パソコンで適切なアプリを使って，まとめてくだ
さい。

** 成績評価方法

** 評価の基準
- 数学的知識の構造化ができているか
- 数学的知識の構造化を適切に表現できるか (構造的文書，マインドマップ，
  図，グラフなどを用いて)

** 履修における留意点
- ノートパソコンを持ち込んでください。
- 教室のWifiインターネット環境は，多人数同時使用の実績がないそうです。
  実際に使ってみないとわからない状態です。状況によっては講義形式が変る
  かもしれません。


** 詳細計画
1. ガイダンス，集合と論理，数理ICT入門 (Webと検索)
2. 集合と論理，数理ICT入門 (デジタルノート)
3. 集合と関数，数理ICT入門 (デジタルノート，URL)
4. 集合と関係，数理ICT入門 (デジタルノート, 共有)
5. 関係とグラフ，数理ICT入門 (Mindmap)
6. 論理的思考とグラフ， 数理ICT入門 (Mindmap)
7. 1変数関数の微分,  数理ICT入門 (数式処理)
8. 1変数関数の微分，数理ICT入門 (数式処理)
9. 1変数関数の積分，数理ICT入門 (数式処理)
10. 多変数関数とベクトル，数理ICT入門 (数式処理)
11. 多変数関数の微分，数理ICT入門 (数式処理)
12. 多変数関数の微分，数理ICT入門 (数式処理)c
13. 多変数関数の積分，数理ICT入門 (数式処理)
14. ベクトルと行列，数理ICT入門 (数式処理)
15. 講義全体のまとめ，デジタルノートの提出


