#+startup: indent show2levels
#+title:
#+author masayuki

* 7/3 練習問題


1. 次の文章を論理式で表わしてください：

   「\( x=2 \) と x=-3 は，\( x^3 +x^2-6x=0 \) の解である。」

2. を証明する手順を示してください。
   1. \( A \vee B  \longrightarrow C \)

   2. \( A \longrightarrow B \vee C  \)
   
3. 次の文章中で，
   - 対象を括弧で括り，
   - 関係を中括弧で括り
   - 主張を論理式っぽく表してください。

   「三角形ABCで，辺ABの長さと辺ACの長さが等しいので，
     三角形ABCは二等辺三角形である，」

   - 二等辺三角形の定義を論理式っぽく示してください。

   - 定義を使って，主張を証明できますか？

4. 次の文章に対し，下問に答えてください:

   「m, n の片方が偶数，他方が奇数のとき，n+m は奇数になる」

   1. 論理式で表してください。
   2. 証明してください
   3. 証明図を書いてください

5. p を素数とし，整数全体の集合を Zとする。

   1. Zを，p個の同値類に分けることができる同値関係を一つ示し，同値関係
      であることを示してください。

   2. p個の同値類の (自然な) 代表元を示してください。



* 7/3 練習問題への答

すみません，式や証明図など，デジタル化できてないものが多いので，
紙で見せます：

1. 次の文章を論理式で表わしてください：

   「\( x=2 \) と x=-3 は，\( x^3 +x^2-6x=0 \) の解である。」


   \( x^3 +x^2-6x=0  \longrightarrow  {x = 2} \vee {x = -3} \)


1. を証明する手順を示してください。
   1. \( A \vee B  \longrightarrow C \)

      1. \(A\)を仮定して，\(C\)を証明するか，

      2. \(B\)を仮定して，\(C\)を証明する.

      仮定に \(\vee\)記号を含まない，より単純な論理式の証明に持ち込む。

   2. \( A \longrightarrow B \vee C  \)

      1. \(A\)を仮定して，\(B\)を証明し，

      2. \(A\)を仮定して，\(C\)を証明する.

      結論に \(\vee\)記号を含まない，より単純な論理式の証明に持ち込む。
   
3. 次の文章中で，
   - 対象を括弧で括り，
   - 関係を中括弧で括り
   - 主張を論理式っぽく表してください。

    (三角形ABC)で，{((辺AB)の長さ) と ((辺AC)の長さ) が等しい} ので，
    (三角形ABC)は (二等辺三角形) である。
    
   - 二等辺三角形の定義を論理式っぽく示してください。

     点A, 点B, 点C, 辺AB, 辺AC, 辺BC,
     二等辺三角形(ABC) <=> 
     辺ABの長さ = 辺ACの長さ 
     辺ABの長さ = 辺BCの長さ
     辺ACの長さ = 辺BCの長さ 
     

   - 定義を使って，主張を証明できますか？

     二等辺三角形(ABC) <=>
     三角形ABC,
     辺ABの長さ = 辺ACの長さ \(\vee\) 
     辺ABの長さ = 辺BCの長さ  \(\vee\) 
     辺ACの長さ = 辺BCの長さ
     
     三角形ABC と 辺ABの長さ = 辺ACの長さ から
     二等辺三角形(ABC)が成り立つ
     
4. 次の文章に対し，下問に答えてください:

   「m, n の片方が偶数，他方が奇数のとき，n+m は奇数になる」

   1. 論理式で表してください。

      
   2. 証明してください
      
   3. 証明図を書いてください

5. p を素数とし，整数全体の集合を Z とする。

   1. Zを，p個の同値類に分けることができる同値関係を一つ示し，同値関係
      であることを示してください。

      n \equiv m  (\mod p)
      n \equiv n (\mod p)
      n \equiv m, m \equiv l => n \equiv l (\mod p)
      n \equiv m <=> m \equiv n (\mod p)
      

   2. p個の同値類の (自然な) 代表元を示してください。

0，1，。。。，p-1
