#+startup: indent show2levels
#+title:
#+author masayuki
** 5/15 アンケートの意見

突然、数学の難易度が上がったような気がして驚きました。次回で今回の内容
について、軽くでも触れていただけるとありがたいです。

PCを所持しておらず、スマホでメモは取りずらいので、手書きでノートを作成
することは可能でしょうか。本日の自習においては、図書館のPCより閲覧しま
した。

集合と関係や順序については理解できました。pythonなどについては難しい部
分もありできない箇所もあったため、もう少し練習していきたいと感じました。

見方が難しい。

わかりやすかった。

自分でやると操作が難しかったです

集合の順序関係は知りませんでした。
これからのレポート提出は共有しているgoogle driveのフォルダに出せばいいですか？

まだ自分には専門的知識がないためとても難しかったです。先生の偉大さを感じました。

colabで、色んなプログラムをやってみたいと思った。また集合について深めれた気がした。

初めての自習だったがやるべきことはできた。

しっかり自主学習できた

Googleドライブについて不明な点がありました。

出席記入忘れました

suzuki@iwate-u.ac.jpにアクセス権を与えることはできたが、リンクを知っている人全員に
アクセス権を与えることはなぜかできなかった。大学のgoogleアカウントだからだろうか？

googleドライブの共有をしたため、許可できているか確認してほしいです。以下は共有リンクです。
https://drive.google.com/drive/folders/1pda22-C-eSsaiQgDISioJCdU2AiFjmFK?usp=drive_link

提出が遅れました。WebClassでの出席登録もできていません。申し訳ありません。

正直アンケートの最後の項目のmarkdown書式がよくわからなかった。

集合の直積についての表し方を知れた。年長関係や勝ち負け関係と集合を組み
合わせて表現しているのが面白かった。集合の特殊な関係についても知れた。
順序集合についても高校では習ったことが無かったので知れて興味がわいた。
あとは、上のアンケートにあるような様々なアプリについて知れたので自主的
に使ってみたい。

少しわからなかった。

集合は内容が進んで難しくなったかように思えるからさらに復習が必要である
ように思った。pythonは全くわからないところからのスタートだから慣れるた
めにももっと自発的に取り組みたいと思った。

授業の内容はすごく楽しいですか、出席やレポート提出のやり方などをもう少
し具体的に教えていただくとありがたいです。

suzuki@iwate-u.ac.jpのリンクが見つからなかった

ファイルを閲覧する方法がわからないもののあって、困りました。
