#+startup: indent show2levels
#+title:
#+author masayuki

2023年4月17日 理化学研究所

* グラフが論理的思考力を高める

** 背景

ノード（頂点）とリンク（辺）で構成されるデータ構造を「グラフ」といいま
す。

これまで、マインドマップ[3]、KJ法のA型図式[4]、概念地図[5]、議論地
図[6]などのグラフは正式の文書ではなく、教育や発想支援のための補助資料
として使われてきました。

実際、これらのグラフを作成していると、「批判的思考力（論理的思考力）」
が向上するという教育的効果が多くの先行研究で示されています。

グラフの中の各ノードを任意のテキストや画像とし、リンクの種類（図1に示
す意味的関係）を規格化して選択入力可能にすることにより、グラフの作成・
編集を容易にするソフトウェアツール「セマンティックエディタ
[7]（Semantic Editor）」を開発してきました。

さらに、従来のテキスト文書の内容をグラフの形の文書でより明確に表現でき
ることに着目し、セマンティックエディタによるグラフの共同作成がGoogle
Docsによるテキストの共同作成よりも簡単であることを既に実証しています注
1）。

** 図1 リンクの種類（意味的関係）

*** 部分全体関係 (集合))
- 部分
- 要素
- 例 (モデル)
*** 談話関係
**** 付加的関係
***** 正付加関係
- 追加
- 背景
- 内容
- 等価
***** 負付加関係
- 対照
- または
- 相違
**** 因果的関係
***** 正因果関係
- 因果
- 推論
- すると
- 目的
- ならば
***** 負因果関係
- 相反
- によらず
- 譲歩
*** 対話行為
**** 返答
- はい
- いいえ
- 解決案
*** 時間関係
- その後
- 同時
- 状況
*** 他の関係
- 対象
- ？

** 説明

*** 文と文の間の関係などは
ISO（国際標準化機構）の国際標準になっており、図の意味的関係の集合はそ
れらの国際標準を参考にして策定したもの。こうした関係の集合は言語に依存
しないと考えられる。

*** 従って、テキストの代わりにグラフを正式の文書として作成・編集・活用すれば、

- 教育や業務、研究における文書処理（文書の作成・編集・活用）の効率が高ま
  るはずです。

- さらに、グラフ作成者の批判的思考力が高まるため、文書処理に限らないさ
  まざまな場面で知的生産性が向上すると考えられます。

*** テキストよりもグラフの方が文書処理の効率が高い

*** グラフを作成すると批判的思考力が高まるのも、

- グラフが論理的な構造を明示的に表現し、
- 操作を容易にしているからだと考えられます。

セマンティックエディタは、論理的な構造の操作をさらに容易にすることで、
グラフのこのようなメリットを増大させると期待されます。

*** しかし、文書をテキストによって表現すること

*** グラフのメリットは、

批判的思考力をはじめとする非認知能力（社会情緒的能力）が高い子どもほど、将来成功する確率
が高いといわれています。

また、批判的思考力に関する標準的なテストを用いて、能力の向上を測定することも比較的容易です。

一般の業務においても、グラフは文書処理の効率と事業成績を向上させると考えられますが、

事業成績の向上には文書処理の効率向上と事業に携わる個人の能力向上以外の要因が多く、
また個人の批判的思考力の向上よりも測定が困難です。

** 研究手法と成果

*** グラフの作成によって批判的思考力を高めるためには

最近の学校教育でグループディスカッション（協調学習）が盛んに行われてい
ることに着目し、二つの高校での実験によって下記の仮説[H]の検証を試みま
した。

仮説[H]：通常の授業においてグループディスカッションの内容を表すグラフ
を生徒が共同作成することは教員の負担を増やすことなく可能であり、それに
よって生徒の批判的思考力が向上する。

テキストよりもグラフの方が文書処理の効率が高く、グラフを作成すると批判的思考力が高まるという先行研究の成果は、大学生以上の大人に関する知見であり、高校生でも同じことが成立するかどうかは不明でした。しかし、実験によって仮説[H]が証明されれば、高校生でもグラフの作成が批判的思考力を高めることが明らかになります。また、高校生にとってもテキストよりグラフの方が作りやすいことが証明はされないものの、示唆されることになります。

2022年10月から2023年1月にかけて、埼玉県の川口市立高校および神奈川県の三浦学苑高校で、1年生の「現代の国語」の授業中のグループディスカッションにおいて、各グループの生徒がセマンティックエディタで議論の内容を表すグラフを共同作成しました（図2）。実験に参加したのは川口市立高校の5クラスと三浦学苑高校の1クラスで、生徒数は合計100余名でした。グループディスカッションの各グループは2～5名でした。川口市立高校の5クラスのうち3クラスと2クラスは別の教員が担当しました。
生徒が作ったグラフの例の図

図2 生徒が作ったグラフの例

サムネイル画像は架空のものに置き換えてある。

まず、2022年10月に1回目の批判的思考力のテスト（CTテスト）を実施した後、グラフの作り方を教員が説明し、2023年1月まで5回の授業において上記のようなグラフの共同作成を行い、その後2回目のCTテストを実施しました。CTテストには、WGCTA（Watson-Glaser Critical Thinking Appraisal）方式の選択問題を用いました。各回のテストは39問または40問からなります。川口市立高校においても三浦学苑高校においても、1回目と2回目のCTテストの問題に重なりはありません。川口市立高校の5クラスは各回に共通のテストを受けています。

グラフの共同作成を行う授業は、教員がグループディスカッションの議題について説明し、それに応じて生徒の各グループがグラフを共同作成しながらディスカッションして、他のグループと教員からのコメントを受けてグラフを修正する、という形を想定しましたが、実際には必ずしもこのパターンに従うわけではなく、グループの間でコメントし合う時間が足りなくなることなどもありました。

実際の授業において、生徒が作ったグラフを見て教員が即座にコメントしていた（テキストの場合はコメントするまでにもっと時間がかかるはずです）ことから、生徒は授業に支障をきたさない程度にグラフ文書を作成できていたといえます。また、教科書の図表などのコピーに注釈を加えた資料を教員が事前に用意して生徒に配布することがありましたが、同様の資料は従来の授業でも作成していたので、グラフの共同作成の導入が教員の準備の負担を増やすことはないと考えられます。グループディスカッションの内容を表すグラフを生徒が共同作成してそのグラフに教員と他の生徒がコメントするという方法は、グループディスカッションを含む多くの授業に容易に導入できるでしょう。

このことにより、仮説[H]の前半（通常の授業においてグループディスカッションの内容を表すグラフを生徒が共同作成することが教員の負担を増やすことなく可能）を示すことができました。また、仮説[H]の後半（それによって生徒の批判的思考力が向上する）も下記のように示されます。

1回目または2回目のCTテストに欠席した生徒を除いたちょうど100名の生徒のCTテストの成績とグラフの操作（リンク作成、リンク編集、ノード作成、ノード編集、ノード移動）の回数のデータを分析しました。ここで、リンク編集とはリンクの種類または向きを変更すること、ノード移動はノードの座標を変更することを指します。両校での各操作の総回数は、リンク作成が1,372回、リンク編集が562回、ノード作成が1,659回、ノード編集が445回、ノード移動が2,521回でした。分析結果の概要は以下の通りです。

(1) グラフ操作の量とCTテストの成績向上との相関関係がある確率は99.73％だった。
(2) 5回の授業でのグラフ操作は、CTテストの成績に影響する要因の8.8％を占めた。
(3) 5種類のグラフ操作のうち、リンク作成とリンク編集、ノード編集がCTテストの成績向上の主な要因だった。
(4) ICTテストの成績向上の両校の平均は3.1％だった。

(1)で、仮説[H]の後半も示すことができました。グラフを共同作成する授業を
5回より多く受ければ（高校3年間で50回ほど受講できると思われます）、グラ
フ操作がCTテストの成績にもたらす影響は、(2)の8.8％より大きくなるはずで
す。また、リンク作成とリンク編集がCTテストの成績向上の主な要因であるこ
とから、リンクの種類を簡単に選択入力できるセマンティックエディタの機能
は批判的思考力の向上に有効だと考えられます。

** 今後の期待

本研究では、
- グラフの共同作成を高校の通常の授業に余分な手間をかけずに導入できるこ
  とと、
- それによる批判的思考力の向上が統計的に有意であることを実証

これは、全国のあらゆる高校で授業にグラフを導入する合理的な根拠になりま
す。

中学校や大学でも同様と予想されます。それによって教育
現場でのグラフの効果が広く周知されれば、一般の業務の現場にもグラフが普
及し、さまざまな場面での知的生産性が永続的に高まり、産業や学術、政治、
文化の発展が加速すると期待できます。

さらにChatGPTのようなテキスト生成AI（人工知能）の普及も、テキストから
グラフへの移行を促進するでしょう。

- 人間とAIとのインタフェースにもグラフを使った方が、人間にもAIにも都合
  が良いはずです。
  
  - グラフは明示的な意味構造を持つため、

    - AIの入力データとしても学習データとしても優れています。

  - グラフを入力して、それを拡張したり変換したり翻訳したりするAIが、グ
    ラフの作成・編集・活用を支援してくれるようになるでしょう。

  - そのようなAIの性能は、大量のグラフのデータを機械学習に用いることで
    向上し続けます。

** 補足説明

    1. グラフ :: 一般にはノードとリンクからなるデータ。本研究で扱うグ
       ラフでは、各ノードは任意のテキストや画像を含み、各リンクは「因
       果」や「例」や「対照」などの意味的関係を表す。

    2. 批判的思考力 ::論理的思考力、つまり事実や概念の内容を論理的・客
       観的に把握し操作する能力のこと。

    3. マインドマップ :: 思考の内容を表現するための、木構造に近い放射
       状のグラフ。

    4. KJ法のA型図式 :: KJ法は川喜田二郎がフィールドワークなどで収集し
       たデータをまとめるために考案した手法。データを記したカードをグ
       ループにまとめた図解がA型図式。それに基づいてテキスト文書（B型
       文章）を作る。

    5. 概念地図 :: ジョセフ・D・ノヴァクらが考案した、概念間の関係を表
       現するグラフ。

    6. 議論地図 :: 議論の構造を視覚的に表すグラフ。結論、前提、共同根
       拠、反対意見、反論、仮定などのノードを含む。

    7. セマンティックエディタ ::グラフを作成・編集するソフトウェアツー
       ル。Personaryアプリの機能として実装されている。Personaryは分散
       PDS（personal data store）ライブラリであるPLR（personal life
       repository）を用いて、パーソナルデータなどを安全かつ安価に保管・
       共有するアプリであり、iOS、Android、Windows、macOS、Linuxで動作
       する。
    

