#+startup: indent show2levels
#+title:
#+author masayuki



[[https://lot.or.jp/project/11662/][グラフ文書を教育に活用することで批判的思考能力が向上第132回オンラインシンポレポート・前半 | 超教育協会 Learning of Tomorrow]]

2023.9.8 Fri

* グラフ文書を教育に活用することで批判的思考能力が向上

** 概要

超教育協会は7月26日、東京大学大学院情報理工学系研究科 附属ソーシャル
ICT研究センター教授の橋田 浩一氏を招いて、「教育におけるAI利用」と題し
たオンラインシンポジウムを開催した。

 

シンポジウムの前半では、橋田氏が教育におけるグラフ文書の活用と効果について講演を行い、後半では、超教育協会理事長の石戸奈々子氏をファシリテーターに、視聴者からの質問を織り交ぜながら質疑応答が実施された。その前半の模様を紹介する。

 

「教育におけるAI利用」

■日時：2023年7月26日　12時～12時55分

■講演：橋田 浩一氏
東京大学大学院情報理工学系研究科
附属ソーシャルICT研究センター教授　

 

橋田氏は、約30分の講演において、批判的思考能力の向上に効果があるグラフ文書の研究について話した。主な講演内容は以下のとおり。

教育におけるAI利用について、「批判的思考力」にフォーカスして説明します。教育学ではBloomの分類というのがあります。これは、学習はどういう段階を追っていくかを説明しています。まずは知識を記憶するところから始まって、理解する、応用する、解析する、分析する、その知識を使って何かを評価する、さらにその知識に基づいてクリエイトすると分類されます。この上層の3つ、分析する、評価する、クリエイトするが批判的思考に相当すると思います。

 

▲　スライド1・分析、評価、クリエイトが
批判的思考に該当する

 

AIができることは何でしょうか。大規模言語モデル（以下、LLM）はテキストで書かれた知識を集約する能力では圧倒的に人間を上回っていますが、それを本当に理解しているのか、色々な場面で応用できるのかとなると、かなり怪しくなってきます。評価はほとんどできてないように見えます。AIは「色々なことをでっちあげる」と言われています。AIとしては知識を組み合わせて答えを生成しているのですが、生成されたものがどのくらいもっともらしいかをAI自身は評価できません。だからそれをそのまま「垂れ流して嘘八百」になってしまうのです。

 

評価ができないと創造はできません。創造するには、たくさん仮説を生み出してその中から良いと思えるものをピックアップして、それをいろいろな知識に照らして修正してという作業を際限なく繰り返さないとなりません。今のAIにはそれができません。リアルな体験を欠いており、論理的な推論もあまりできません。創造には仮説検証やメタ認知が必要ですがそれができない。これが現在のAIです。

 

それでも、やはりあらゆる知識を集約できる能力は非常に強力で、足りない機能は補えるため、LLM自体の社会的なインパクトは非常に大きいと思います。ではどういうインパクトでしょうか。AIはあらゆる知識を集約するわけですが、その知識はあらゆるサービス、あらゆるコンテンツを含みます。そうすると、あらゆるサービス、あらゆるコンテンツに対する「個人向けポータル」にAIがなっていきます。

 

▲　スライド2・AIはあらゆるサービスと
コンテンツに対する
個人向けポータルになっていく

 

つまりAIがパーソナライズされて、一人一人のユーザーに対して無数のサービス、無数のコンテンツにアクセスするためのポータルとして機能します。そうすると、あらゆるデータがAIにとって扱いやすい様式になるという方向性が見えてきます。私はそれを「AI Optimization（AIO）」と呼んでいます。これはSEOのもじりです。SEOは特定のウェブサイトを検索エンジンに引っかかりやすくするものですが、AIOはある知識、あるサービスをAIに処理しやすくするということです。その一環として人間はどういったコンテンツを作るべきかという話をこれからします。それがグラフ文書です。
因果関係含めた内容を効率的に表現するのが「グラフ文書」

そもそも人間の文書読解能力が低いということは、いろいろな人が指摘しています。アメリカの大学に留学すると、毎日膨大なドキュメントを読まされて、たくさんレポートを書かされるという話を聞きますが、それはごく一部のエリート大学で、ほとんどの大学はそうではありません。普通は在学中に批判的思考力がほとんど伸びないと言われています。

 

OECDの国際成人力調査（PIAAC）の一環で、読み書きの能力を評価する問題を紹介します。

 

▲　スライド3・読み書きの能力と
数的な能力を評価する調査

 

保育園のルールで、お子さんを午前9時までに連れてきてください、お昼寝用に小さな毛布などをお持ちくださいと書いてあり、これを読んで問いに答えなさいというものです。子供は遅くとも何時までに保育園に来ればよいかという簡単な問いですが、このようなレベルの問題ですらOECD諸国の大人の平均正答率はわずか40％です。いかに普通の人が文章を読めないかがわかります。日本は諸国のなかでトップレベルです。年齢でプロットしてもOECDの平均をずっと上回っています。

 

ただ、「ロボットは東大に合格するか」という東ロボプロジェクトの結果を見ると7年前のAIに負けています。ChatGPTに比べたらもっと負けているでしょう。高校生も大人も文章を読めていません。そこで、グラフ文書を使ったらよいのではないかという話になります。

 

▲　スライド4・因果関係等を矢印で示し、
内容を効率的に表現するグラフ文書

 

推論、対象、例、因果などの関係が矢印で示されていますが、こうした関係を選択入力することで任意のテキストの内容をより効果的に表現できるのがグラフ文書の特徴です。似たようなものは色々あります。日本にはKJ法のA型図式というのがあり、フィールドワークで収集した情報をカードにしてまとめていきます。KJ法はこうした図式を作ってからB型の正式なテキストを作るという手順ですが、いかにも面倒な感じがします。また、リンクの意味が明示されないため、A型図式でテキスト文書を代替することができません。次にこれはアメリカで考案されたコンセプトマップというものです。

 

▲　スライド5・コンセプトマップは
手間がかかり作成の効率が低い

 

これはリンクの意味をそのつどユーザーが自由テキスト入力するというやり方で、けっこう面倒です。手間がかかって作成の効率が低い。リンクのラベルが標準化されていないため、複数の著者の間で意味が統一されず誤解が生じやすいという難点もあります。

 

一方、一般にグラフを使うと良いことがあります。まず、わかりやすく作りやすく質が高い。それから地頭が良くなります。批判的思考力が高まることは先行研究で確認されています。

 

まず、グラフは分かりやすい。この例では、普通のテキストだと読むのに10秒くらいかかるのが、グラフだと非常に単純な一本線の構造をしているため、0.5秒くらいで概要が分かります。

 

▲　スライド6・グラフ文書の意味構造は
明確で普通の文章よりわかりやすい

 

詳細まで理解するには10秒くらいかかりますが、パッと見て全体を把握するのは0.5秒くらいでできるのが利点です。それから、グラフは作りやすい。例えば、頭が痛かったことが原因で頭痛薬を飲み、それで頭痛が治った。頭が痛い一方で胃の調子はよかったというところまでグラフを作ったところで、胃の調子がよかったことも頭痛薬を飲んだ原因なのではないかということに気づいたとします。頭痛薬は胃に悪いので胃の調子が悪い時には飲みたくありませんが、胃の調子が良かったから頭痛薬を飲んだのだということです。それを思いついたら、どうやってグラフに反映するかは簡単で、リンクを入れればよいだけです。

 

▲　スライド7・因果関係を付け足すには
リンクを入れればよい

 

でも同じことをテキストでやろうとすると大変です。胃の調子が良かったことも頭痛薬を飲んだ原因ではないかと気付いた時に、これをどうやってテキストに反映させるかは簡単ではありません。うまい言い方をすぐに思いつけばよいですが、場合によってはそれに何十秒もかかかってしまいます。グラフの方がテキストより作りやすいだろうと想像できます。

 

それから、グラフの方が質が高いことも分かっています。25年前に和歌山大学のグループがランダム化比較実験をしています。実験群の各被験者はグラフを作ってからそれに基づいてテキストを作成する、統制群の各被験者はいきなりテキストを作成する。いずれも30分でやってくださいという実験の結果、できたテキストを比べてみると、実験群の方が出来が良かった。与えられたテーマに関連する論点が多いということと、推論の連鎖が長いという客観的な基準において、実験群の方が質が高いテキストを作成しました。

 

しかし、こうしたエビデンスにもかかわらず、グラフが本当にわかりやすくて作りやすいのかと多くの人が疑問に思うようです。そこで、論より証拠ということで、3年前にうちの研究室で実験しました。実験は2種類あって、まずひとつは同期的な共同作業です。2人が面と向かって話をしながら、それぞれのパソコンで共有文書を編集します。この共有文書はテキストの場合とグラフの場合があります。制限時間を同じにしてお題を与えて、共有テキストと共有グラフを作らせてみました。できたものを論点の個数や推論の長さなどの評価基準に照らしてみると、グラフの方がテキストより優れていることがわかりました。これは対面での共同作業ですが、対面せずに最初の人が半分くらい文書を作り、2番目の人がそれを完成させるという非同期の共同作業でも調べてみました。結果は同じで、グラフの方がテキストより優れていました。客観的にグラフの方が作りやすいということがわかります。共同作成するには相手が作ったコンテンツを理解する必要がありますから、作りやすいということはわかりやすいということでもあるでしょう。

 

グラフを作ると地頭がよくなるという研究は山ほどあります。一方、批判的思考力が高まれば学業成績も上がることがさまざまな研究によって分かっています。以上のように、先行研究でグラフはテキストより作るのが簡単であるということと、地頭が良くなることが明らかになっています。

 

▲　スライド8・先行研究によって
グラフ文書のメリットが明らかになった
教育現場でグラフ文書の実験を実施

テキストよりグラフの方が作りやすいのだから日常の業務でテキストの代わりにグラフを作れば共同文書作成の効率が高まります。共同文書作成はほぼ知的共同作業そのものです。論文を書いたり査読したりする、業務計画を作るということなので、多くの仕事の効率が高まります。また、グラフをいじっていると地頭が良くなるので、それによって社会全体でみんなの頭を良くしたい。

 

そのために、新たな実験をしました。グラフはテキストより作るのが簡単だという実験結果を先ほどお話しましたし、グラフをいじっていると頭がよくなるという先行研究もありますが、これらは別々の実験なので果たして実際の現場でこのふたつのメリットを両立させるような条件が成立するかということはやってみないと分かりません。そこで今回は教育現場での実験です。生徒がグループディスカッションの内容をグラフで共同作成することが、通常の授業で可能であることを確かめました。同時に、グラフをいじるほど生徒たちの批判的思考力が高まることを確認しました。これはその実験の内容ですが、2022年10月から2023年1月まで行いました。

 

▲　スライド9・高校で実施した
グラフ文書の教育効果に関する実験の概要

 

2つの高校に協力してもらい、1年生の6クラス約100人が参加しました。実験の手順は、まず批判的思考力の試験を行い、それからグラフを使った授業を5回やりました。そのあと、もう一回別の批判的思考力の試験を行いました。グラフを使った授業というのは、「現代の国語」という昨年度高校の課程に導入された新しい科目で、学習指導要領によれば、グループディスカッションをしなさいとなっているため、最初からグループディスカッションをする予定でした。2人から5人くらいのグループでディスカッションをするのですが、そのディスカッションの内容をグラフ文書として各グループの生徒が共同作成します。それに対して先生やほかのグループの生徒がコメントして、そのコメントを取り入れるようにしてグラフを修正します。こういったことを5回やりました。

 

結果は２つあります。ひとつは、余分なコストも支障もなくグラフ文書を通常の授業に導入できるということです。具体的には先生の負担が増えないということです。今まで作ったことのないような資料を用意する必要もありません。生徒は、いきなりまあまあのグラフを作ることができます。矢印の向きが逆だったりすることがありますが、生徒が作ったグラフを先生がパッと見て、瞬時に有意義なコメントをすることができます。このように、授業は支障なく成立しています。

 

もうひとつは、グラフをたくさんいじっている生徒ほど、批判的思考力が高まっているということです。グラフの操作はノードやリンクを作ったり編集したりする作業です。そのグラフ操作の量と、批判的思考力試験の成績の伸びの間の相関係数は0.3とあまり大きくはないですが、その相関が成立する確率は99.73％。グラフを使った授業を5回しか行っていないので相関係数が低いのは当たり前です。同じような授業を高校3年間で50回くらいはできるでしょう。そうすると相関係数は0.7くらいまで高まるはずです。

 

この実験により、高校教育へのグラフ文書の導入は現実的に可能で且つ教育効果を高めることが明らかになりました。これは教育の話ですが、一般業務の場面でも、自社の社員にグラフを使わせれば、事業計画のクオリティが高まって且つ社員の頭もよくなるので、組織の業績が高まるであろうということは容易に想像できます。まず教育現場から始めて、社会全体にグラフ文書を広げることができるのではないかと考えています。

 

次に、AIをどう使えばよいかという話です。より形式的なコンテンツ、文書の方が人間にとって扱いやすいのですが、おそらくAIにとっても扱いやすいはずです。

 

▲　スライド10・形式的なコンテンツの方が
人間にもAIにも扱いやすい

 

より形式的というのは、文書の表面的な構造とその意味とのマッピングがより単純であり、文脈依存性が小さいということです。グラフ文書の方が人間にとっては扱いやすく、それをいじっていると頭がよくなるということをお話しましたが、それはグラフ文書の方がテキスト文書より形式的だからでしょう。AIの場合にも同じことが成立すると考えられます。つまりテキストよりも明確に構造化されたグラフを操作する方が、AIにとっても楽だし性能も高いでしょう。グラフのデータで学習するとAIの能力が高まることも期待できます。実際LLMは、プログラムのコードを生成する方が自然言語のテキストを生成するより得意です。これはプログラミング言語が形式言語だからだと思います。

 

もうひとつargument mapというグラフがありますが、concept mapよりも高度に形式化されています。おそらくそのせいでconcept mapよりも批判的思考力を向上させる効果が大きいことがわかっています。

 

人間とAIがグラフ文書を共同作成するという使い方がおそらく最も有意義なAIの使い方で、これを教育の場面でもできるのではないか。人間とAIがグラフ文書を共同作成することで、人間にとってはよりよいコンテンツができるし、且つ地頭が良くなります。AIについても性能の向上が期待できます。グラフ文書が日々の業務の現場で作られるようになれば、それをAIの学習にも使うことで、よりクオリティの高いコンテンツで学習したAIが、より高い性能を発揮します。そして人間の頭も良くなります。結果、社会全体の生産性も高まることになります。批判的思考力を高めるというのは教育効果なので、当然ながら、能力が低いほど批判的思考能力や生産性の向上の幅は大きい。したがって格差の解消に繋がるでしょう。

 

▲　スライド11・グラフ文書を使うことの
メリットや効果

 

では話をまとめます。グラフをいじっていると批判的思考能力が向上することは先行研究で明らかになっています。それから、3年前の実験でグラフ文書はテキスト文書より作りやすいことが分かっています。こうしたメリットにはオントロジーによって意味関係などが規格化されていることが貢献していると思います。それによってテキストの内容をより効率的に表現することができます。授業で使った場合には学習すべき内容をより効率的に表現できるため、授業の効率も高まるはずです。

 

今回行った実験は、グラフの方が作りやすいという効果と頭が良くなる効果が現場で両立することを示しました。グループディスカッションでのグラフの共同作成を生徒にやらせることによって、教員の負担を増やさず授業が支障なく成立して、生徒の批判的思考力が高まります。今回は授業を5回しか行わなかったのですが、3年通して行えば批判的思考能力が10％以上伸びて、学力が100点満点で5点くらい伸びるのではないかと思います。今回の実験は高校1年生で行ったので、この結論は高校生以上に対して有効だと思いますが、接続詞が使えればグラフ文書を作れると思うので、おそらく小学校高学年以上に妥当するでしょう。グラフ文書をAIと共同作成するのはメソッドとして明確なので、すぐにでも現場に導入できて授業を滞りなく行えて、且つ批判的思考能力向上という教育効果が見込めることが今回分かりました。AIを使えば、壁打ちみたいな形で自習にも使えるし、複数の人間とAIが協力してグラフ文書を作るというやり方でも、AIの方が圧倒的に知識が多いため、人間の見落としを防いでさまざまな論点に関してさまざまな論考を巡らせて、よりよいコンテンツを作ることに貢献できるのではないかと思います。今回お話したツール、セマンティックエディタはPersonaryというアプリに組み込まれていて、”Personary”で検索すれば出てきます。このQRコードをスキャンしてもOKです。興味ある方はぜひいじってみてください。

 

▲　スライド12・PersonaryのQRコード

 

＞＞　後半へ続く
おすすめ記事

    第162回オンラインシンポ「生成AIを活用するために必要な情報活用能力を育む」開催のお知らせ
    第162回オンラインシンポ「生成AIを活用するために必要な情報活用能力を育む」開催のお知らせ

    2024.6.25 Tue
    超教育CHANNEL・第153回オンラインシンポ 「学校現場における生成AIの可能性－授業や校務で効果的に活用するアイディア－」
    超教育CHANNEL・第153回オンラインシンポ 「学校現場における生成AIの可能性－授業や校務で効果的に活用するアイディア－」

    2024.6.21 Fri
    授業でも校務でも、生活指導や生徒の健康相談にも</br>第156回オンラインシンポレポート・後半
    授業でも校務でも、生活指導や生徒の健康相談にも
    第156回オンラインシンポレポート・後半

    2024.6.21 Fri
    授業でも校務でも、生活指導や生徒の健康相談にも</br>第156回オンラインシンポレポート・前半
    授業でも校務でも、生活指導や生徒の健康相談にも
    第156回オンラインシンポレポート・前半

    2024.6.21 Fri
    超教育協会メールマガジンNo.070
    超教育協会メールマガジンNo.070

    2024.6.17 Mon
    超教育CHANNEL・第152回オンラインシンポ「教育特化型メタバース『3D教育メタバース』～21世紀を生き抜くための教育の多様性をめざして」
    超教育CHANNEL・第152回オンラインシンポ「教育特化型メタバース『3D教育メタバース』～21世紀を生き抜くための教育の多様性をめざして」

    2024.6.14 Fri
    AIと「ものづくり」で地域と一緒に学生が育つ高専に</br>第155回オンラインシンポレポート・後半
    AIと「ものづくり」で地域と一緒に学生が育つ高専に
    第155回オンラインシンポレポート・後半

    2024.6.14 Fri
    AIと「ものづくり」で地域と一緒に学生が育つ高専に</br>第155回オンラインシンポレポート・前半
    AIと「ものづくり」で地域と一緒に学生が育つ高専に
    第155回オンラインシンポレポート・前半

    2024.6.14 Fri

他カテゴリーを見る

    お知らせ
    プロジェクト
    コラム・インタビュー
    関連ニュース

    最新情報 活動報告 コラム・インタビュー 

超教育協会とは

    設立趣旨 推進体制 事業内容 入会のご案内 財務状況 参加団体メッセージ お問い合わせ メディア掲載 メールマガジン 

© 2018 Learning of Tomorrow
